### ISSUE TITLE
./PINGPONG: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by ./PINGPONG)

### ISSUE THREAD

**Issue by OneNov0209** [CryptoNodeID/pingpong#1]
![Screenshot_2024-04-20-00-37-49-940-edit_com server auditor ssh client](https://github.com/CryptoNodeID/pingpong/assets/95606017/98b2cfb7-5604-4bff-93a7-85afeaf48282)
Help me please

**Comment by GyaFirdan33** [comment]
same like me, maybe it doesnt support ubuntu 20.04

**Comment by BillyJunID** [comment]
> ![Screenshot_2024-04-20-00-37-49-940-edit_com server auditor ssh client](https://private-user-images.githubusercontent.com/95606017/324039286-98b2cfb7-5604-4bff-93a7-85afeaf48282.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQxOTgwNjMsIm5iZiI6MTcxNDE5Nzc2MywicGF0aCI6Ii85NTYwNjAxNy8zMjQwMzkyODYtOThiMmNmYjctNTYwNC00YmZmLTkzYTctODVhZmVhZjQ4MjgyLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI3VDA2MDI0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAzZGZmNjM2YzJlNmNhNmMyNjg4OTIwM2UyYTcxMjcxYjY1Zjg2Njg1OWJhMzVhZjg0ODliNDIyZWZhMmZiOWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.WGTh6Hez5uVmIn6zRI2flLV9Gm9qTY3pv7bN9ZvBl-k) Help me please

you will find this error if you use Ubuntu 20.04
to resolve it, simply execute below command

```
sudo echo "deb http://security.ubuntu.com/ubuntu jammy-security main" >> /etc/apt/sources.list
sudo apt -qy update
sudo apt -qy install libc6
```

for more info and update, you can join our telegram channel https://t.me/CryptoNodeID

**Comment by OneNov0209** [comment]
![Screenshot_2024-04-27-14-11-30-380-edit_com android chrome](https://github.com/CryptoNodeID/pingpong/assets/95606017/6f6c2892-c54e-40d5-8243-e3107cafcb4a)
Already run
